{"id": "8653799151755006", "version": "1.1", "error": {"code": -32000, "name": "Server error", "message": "\"local variable 'gc' referenced before assignment\"", "error": "Traceback (most recent call last):\n  File \"/kb/module/bin/../lib/MetagenomeUtils/MetagenomeUtilsServer.py\", line 101, in _call_method\n    result = method(ctx, *params)\n  File \"/kb/module/lib/MetagenomeUtils/MetagenomeUtilsImpl.py\", line 82, in file_to_binned_contigs\n    returnVal = binned_contig_builder.file_to_binned_contigs(params)\n  File \"/kb/module/lib/MetagenomeUtils/Utils/MetagenomeFileUtils.py\", line 681, in file_to_binned_contigs\n    contig_bin = self._generate_contig_bin(bin_id, file_directory, assembly_contigs)\n  File \"/kb/module/lib/MetagenomeUtils/Utils/MetagenomeFileUtils.py\", line 317, in _generate_contig_bin\n    gc, sum_contig_len, cov = self._generate_contig_bin_summary(bin_id, file_directory)\n  File \"/kb/module/lib/MetagenomeUtils/Utils/MetagenomeFileUtils.py\", line 262, in _generate_contig_bin_summary\n    log(f'generated GC content: {gc}, Genome size: {sum_contig_len} ')\nUnboundLocalError: local variable 'gc' referenced before assignment\n"}}